name: "🐞 Bug"
description: "버그 제보"
labels: ["bug"]
body:
  - type: textarea
    id: why
    attributes:
      label: 왜
      description: 증상, 재현 절차
    validations:
      required: true

  - type: textarea
    id: what
    attributes:
      label: 무엇을
      description: 기대 동작, 예상 범위
    validations:
      required: true
