name: "🏔️ Epic"
description: "큰 기능 단위 또는 이니셔티브"
labels: ["epic"]
body:
  - type: textarea
    id: why
    attributes:
      label: 왜
      description: 배경, 필요성
    validations:
      required: true

  - type: textarea
    id: what
    attributes:
      label: 무엇을
      description: 목표 상태, 예상 범위
    validations:
      required: true

  - type: input
    id: start_date
    attributes:
      label: 시작일
      placeholder: "YYYY-MM-DD"
    validations:
      required: true

  - type: input
    id: due_date
    attributes:
      label: 마감일
      placeholder: "YYYY-MM-DD"
    validations:
      required: true
