name: "✨ Feature"
description: "새로운 기능 추가"
labels: ["feature"]
body:
  - type: textarea
    id: why
    attributes:
      label: 왜
      description: 배경, 필요성
    validations:
      required: true

  - type: textarea
    id: what
    attributes:
      label: 무엇을
      description: 기대 동작, 예상 범위
    validations:
      required: true
